CREATE TABLE IF NOT EXISTS farms (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    location VARCHAR(255),
    leader_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_leader FOREIGN KEY (leader_id) REFERENCES users (id) ON DELETE SET NULL
);